[project]
name = "b3dtools"
description = "B3D Tool example package"
version = "0.1.1"
authors = [
    { name = "Kristian Botnen", email = "kristian@botnen.org" }
]
dependencies = []

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
